//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryISP17.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.ReaderBook = new HashSet<ReaderBook>();
        }
    
        public int Id { get; set; }
        public string TitleBook { get; set; }
        public Nullable<int> IdAuthor { get; set; }
        public Nullable<int> IdPublishingHouse { get; set; }
        public Nullable<int> YearOfPublication { get; set; }
        public Nullable<int> NumberOfPages { get; set; }
        public Nullable<int> IdGenre { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual PublishingHouse PublishingHouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReaderBook> ReaderBook { get; set; }
    }
}
